spring:
    datasource:
        url: jdbc:postgresql://localhost:5432/ovata
        username: postgres
        password: postgres
        auto-commit: false
        hikari:
            auto-commit: false
